version: '3.8'

# Development docker-compose
# Use this for local development with hot reload

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wichita-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - wichita-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wichita-frontend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_GAME_TITLE=Wichita to the Moon [DEV]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - wichita-network
    depends_on:
      - backend
    command: npm run dev

networks:
  wichita-network:
    driver: bridge
