version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wichita-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "3001:3001"
    networks:
      - wichita-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wichita-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Use relative URLs - API is proxied through nginx
      - NEXT_PUBLIC_API_URL=
      - NEXT_PUBLIC_GAME_TITLE=Wichita to the Moon
    ports:
      - "3000:3000"
    networks:
      - wichita-network
    depends_on:
      - backend

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: wichita-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - wichita-network
    depends_on:
      - frontend
      - backend

networks:
  wichita-network:
    driver: bridge
